server:
  port: 8081
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example20231016.todo_3

jwt:
  secret: HTxNVfRmOoAVwzRId8oGVwZjUsC9FTOUsPyZaU4JV6gTs87nP+mxoy4DB1dpFLI5fVIiyIaXuJyRsIyRtSOgwIjppRR9YUHB+ggfSjtI1uSW7dfheY8fVGEWAgewZLoWQk6Gw+cl41rkRqCxJWttwC75aSVl43AzPJ5H34Uq1U85hP32zRh0R6r3lMeOI9LApEt30G246Ckl+0jeZOw84wssNIBmhS141HpUfA4ubNaNHmQy3lZrYRNSuvG5jSojUlGjBoSUpJeTJsUWJ2eDOKbpsVbUWthQH+13jyu7v5yp1EaiRnWevR2aAqgpgBRdi84EX6y4FYhFkpmkqUX67g==
  access_token:
    expiration: 3600 # in seconds
  refresh_token:
    expiration: 604800 # in seconds



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/www_RBAC_com?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456

  jackson:
    #日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      #格式化输出
      indent_output: true
      #忽略无法转换的对象
      fail_on_empty_beans: false
    #设置空如何序列化
    defaultPropertyInclusion: NON_EMPTY
    deserialization:
      #允许对象忽略json中不存在的属性
      fail_on_unknown_properties: false
    parser:
      #允许出现特殊字符和转义符
      allow_unquoted_control_chars: true
      #允许出现单引号
      allow_single_quotes: true
